---
- name: Update apt packages and ensure apt list directory exists
  hosts: all
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Ensure apt lists directory exists
      file:
        path: /var/lib/apt/lists
        state: directory
        mode: '0755'
