---
- name: Update apt packages
  hosts: all
  become: yes
  tasks:
    - name: update apt list
    apt:
      update_cache: yes
    - name: packages | ensure apt list dir exists
  file:
    path: /var/lib/apt/lists/
    state: directory
    mode: 0755
