---
- name: Update Nginx Configuration
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Stop Nginx
      systemd:
        name: nginx
        state: stopped
      ignore_errors: yes

    - name: Remove old Nginx configuration file
      file:
        path: /etc/nginx/nginx.conf
        state: absent

    - name: Copy new Nginx configuration file
      template:
        src: nginx.conf.j2  # Adjust this to your template path
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'

    - name: Disable default site configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Start Nginx
      systemd:
        name: nginx
        state: started
