---
- name: Uninstall Apache2 from Ubuntu
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Stop Apache2 service
      systemd:
        name: apache2
        state: stopped

    - name: Disable Apache2 service
      systemd:
        name: apache2
        enabled: no

    - name: Remove Apache2 package
      apt:
        name: apache2
        state: absent
        purge: yes

    - name: Remove remaining Apache2 configuration files
      file:
        path: /etc/apache2
        state: absent
        recurse: yes

    - name: Remove Apache2 logs
      file:
        path: /var/log/apache2
        state: absent
        recurse: yes

    - name: Remove Apache2 HTML files
      file:
        path: /var/www/html
        state: absent
        recurse: yes

    - name: Remove Apache2 systemd service files
      file:
        path: /lib/systemd/system/apache2.service
        state: absent

    - name: Remove other potential Apache2 directories
      file:
        path: /usr/lib/apache2
        state: absent
        recurse: yes
      when: ansible_os_family == "Debian"
