---
- name: Update apt packages, ensure apt lists directory exists, and upgrade packages
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
